@startuml pumlDump

' class Book {
'     String name
'     int price

'     void aaa()
' }
' class Computer
' abstract class TangibleAsset
' abstract class Asset
' interface Thing

' TangibleAsset <|-- Book
' TangibleAsset <|-- Computer
' Asset <|-- TangibleAsset

' Thing <|.. TangibleAsset

class Book extends TangibleAsset{
    String name
    int price
}
class Computer extends TangibleAsset
abstract class TangibleAsset extends Asset implements Thing
interface Thing{
    aaa()
}

@enduml